name = "halalend/halalend-protocol"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'halalend/halalend-protocol'"

[repository]
user = "halalend"
project = "halalend-protocol"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.1-beta"
source = "github"

[config]
